[tool.pylint.messages_control]
disable = [
  "C0330",
  "C0326",
  "too-many-locals",
  "too-few-public-methods",
  "cell-var-from-loop",
  "invalid-name",
  "too-many-arguments",
  "too-many-ancestors"
]

[tool.isort]
profile = "black"
