[tool.pylint.messages_control]
disable = [
    "too-few-public-methods",
    "invalid-name",
    "too-many-arguments"
]

[tool.isort]
profile = "black"

[tool.pylint.master]
extension-pkg-whitelist = ['cv2']
